#!/usr/bin/env php
<?php
/*
 * This file is part of Mezon PHP Framework.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require('vendor/autoload.php');

\Mezon\Cli\Tool::run();
